# Config used only for server_test.go
---
certs:
  CAFile: ../../.config/ca.pem
  ServerCertFile: ../../.config/server.pem
  ServerKeyFile: ../../.config/server-key.pem
  ClientCertFile: ../../.config/client.pem
  ClientKeyFile: ../../.config/client-key.pem
  UserCertFile: ../../.config/user.pem
  UserKeyFile: ../../.config/user-key.pem
  NobodyCertFile: ../../.config/nobody.pem
  NobodyKeyFile: ../../.config/nobody-key.pem
  ACLModelFile: ../../.config/model.conf
  ACLPolicyFile: ../../.config/policy.csv
server:
  Address: 127.0.0.1:0
  MaxStoreBytes: 1024
  MaxIndexBytes: 1024
