certs:
  ca_file: ./.config/ca.pem
  server_cert_file: ./.config/server.pem
  server_key_file: ./.config/server-key.pem
  client_cert_file: ./.config/client.pem
  client_key_file: ./.config/client-key.pem
  user_cert_file: ./.config/user.pem
  user_key_file: ./.config/user-key.pem
  nobody_cert_file: ./.config/nobody.pem
  nobody_key_file: ./.config/nobody-key.pem
  acl_model_file: ./.config/model.conf
  acl_policy_file: ./.config/policy.csv
servers:
  - node_name: "server1"
    bootstrap: true
    join_addr: null
    address: 127.0.0.1
    log_directory: "data/server1"
    serf_port: 8400
    rpc_port: 50050
    gateway_port: 8080
    latitude: 45.404476
    longitude: -71.888351

  - node_name: "server2"
    bootstrap: false
    join_addr:
      - "127.0.0.1:8400"
    address: 127.0.0.1
    log_directory: "data/server2"
    serf_port: 8401
    rpc_port: 50051
    gateway_port: 8081
    latitude: 45.508888
    longitude: -73.561668

  - node_name: "server3"
    bootstrap: false
    join_addr:
      - "127.0.0.1:8400"
    address: 127.0.0.1
    log_directory: "data/server3"
    serf_port: 8402
    rpc_port: 50052
    gateway_port: 8082
    latitude: 46.829853
    longitude: -71.254028
