# Config used only for resolver_test.go
---
certs:
  CAFile: ../../.config/ca.pem
  ServerCertFile: ../../.config/server.pem
  ServerKeyFile: ../../.config/server-key.pem
  UserCertFile: ../../.config/user.pem
  UserKeyFile: ../../.config/user-key.pem
  ACLModelFile: ../../.config/model.conf
  ACLPolicyFile: ../../.config/policy.csv
servers:
  - Address: 127.0.0.1
